
# Runs tests on 1 environment: demo. The Azure DevOps account does not have free hosted parallelism.

# No deploy step, only builds and runs tests, because it is test framework only
# Mac / Linux compatible

trigger:
  branches:
    include:
      - main

jobs:

  - job: TestDemo
    displayName: 'Run tests on Demo server'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      ENVIRONMENT: 'demo'
    steps:
      - script: |
          echo "Running tests on $(ENVIRONMENT)"
          ./run_tests.sh $(ENVIRONMENT)
        displayName: 'Run OpenMRS tests on Demo'

